# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-zollstock

# >> macros
# << macros

Summary:    App to use your device as a ruler
Version:    0.1.4
Release:    1
Group:      Qt/Qt
License:    GPLv2
BuildArch:  noarch
URL:        https://github.com/black-sheep-dev/harbour-zollstock
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-zollstock.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   libsailfishapp-launcher
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.3
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  qt5-qttools-linguist
BuildRequires:  desktop-file-utils

%description
Sailfish OS app to use your device as a ruler

  %if "%{?vendor}" == "chum"
  PackageName: Zollstock
  Type: desktop-application
  Categories:
      - Utility
  Custom:
      DescriptionMD: https://github.com/black-sheep-dev/harbour-zollstock/raw/master/README.md
      Repo: https://github.com/black-sheep-dev/harbour-zollstock/
  Icon: https://raw.githubusercontent.com/black-sheep-dev/harbour-zollstock/master/icons/172x172/harbour-zollstock.png
  Screenshots:
      - https://github.com/black-sheep-dev/harbour-zollstock/raw/master/metadata/screenshot01.png
  Url:
      Donation: https://www.paypal.com/paypalme/nubecula/1
  %endif


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%defattr(0644,root,root,-)
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
